### ISSUE TITLE
Blackmagic only?

### ISSUE THREAD

**Issue by krisrok** [keijiro/Klinker#1]
I guess the APIs are quite different, so there is no support in sight for say Deltacast cards?

**Comment by keijiro** [comment]
Right. It's difficult to add support for different APIs.

I'm thinking of implementing another plugin for AJA cards (it's also popular in Japan), but I've never heard about Deltacast.

**Comment by krisrok** [comment]
Some say it's one of the best cards on the market. But it's far less popular than e.g. Blackmagic's products.

It was a long shot :) I'll try to get it to work with the AVPro Live Camera plugin.

**Comment by fingerx** [comment]
@keijiro  Can you add support datapath card？ thanks

**Comment by keijiro** [comment]
Datapath? Hmm, I have used their video wall solutions, but I didn't know that they're also producing capture cards.

Honestly, I have no motivation to add support for their cards. Anyway, thanks for the input. I think I should do more research on the market share of capture cards.

**Comment by fingerx** [comment]
@krisrok thank you very much. Feel more use of blackmagic and datapath,aja.

**Comment by krisrok** [comment]
There is the AVPro Live Camera plugin which supports a lot of capture cards. (Not really Deltacast though)

**Comment by keijiro** [comment]
I'm closing this issue now as "not relevant". Please feel free to reopen it for further problems.

FYI, I was looking into AJA, but I can't disclose anything about it for the sake of NDA. If I develop something with it, I can't make it opensourced.
