### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by dv-anomaly** [keijiro/Klinker#10]
Do you have any plans to add Linux support for this plugin?

**Comment by keijiro** [comment]
I'm not actively working on this project due to the COVID situation (I can't use the SDI/DeckLink hardware in the office as it's closed). Please don't expect any addition for a while (1 - 2 years? I have no idea about it.)

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
