### ISSUE TITLE
Still in being maintained ?

### ISSUE THREAD

**Issue by whitespeed** [keijiro/Klinker#2]
Is there a roadmap for the plugin ?

**Comment by keijiro** [comment]
I'm still struggling to find a reasonable goal. It's hard to provide an optimal solution for SDI with this plugin due to the limitation of DeckLink products. I have to find a middle ground.

How do you want to use the plugin? What features do you want in the plugin? Any input is welcomed.

**Comment by grigM** [comment]
Hello Keijiro! Thank you for amazing stuff you make for unity community! 
But a want ask a question - is there any chance to make this plugin for "Decklink" 
capture work on osx ?

**Comment by keijiro** [comment]
@grigM It's possible. I just thought that nobody is using DeckLink with Mac. Do you use it? How do you install it? PCIe thunderbolt box, previous generation Mac Pro or Hackintosh?

**Comment by grigM** [comment]
@keijiro I'm use external Intensity Shuttle device (usb3/thunderbolt2) and looks like it works thru the same DeckLink library as PCI capture cards.  Already tested my devices in openframeworks with  this addon [https://github.com/hanasaan/ofxDeckLink].

**Comment by keijiro** [comment]
@grigM Thanks for the response. Yes, it would work with Intensity. It's a little bit troublesome to add macOS support though.

**Comment by whitespeed** [comment]
@keijiro Thanks for your response.  I try to use this to live mini-soccer matches with 360 4K resolution video.  Maybe some my usage could be considered. :)
1. High resolution with input and output
2. Automatic input mode detection
3. Audio support
4. Multiple cards support
5. Internal and external keyer supported
6. Low latency output (I try to write native plugin to READPIXEL but still too slow)

**Comment by keijiro** [comment]
@whitespeed Thank you for the valuable feedback. So, in your case, doesn't it need genlock or timecode?

All the items excepting 3 (audio supports) are possible. Adding audio input/output support without introducing noise is quite tough.

**Comment by whitespeed** [comment]
@keijiro Yes I forgot the timecode and genlock for multi sync. However I think recoding voice from microphone is not necessary, maybe need to write some native sound code to get pcm data from AudioListener. So no need to worry about noise. LOL

**Comment by keijiro** [comment]
@whitespeed Thanks. Just one more question. Is it possible to replace the solution with NDI? From the experience on this plugin, I got the impression that NDI is much easier to use and good enough in most cases. I start thinking that I should invest more time to improve and enhance the NDI plugin than building a new SDI solution (this plugin).

**Comment by whitespeed** [comment]
@keijiro Sorry for late response. NDI is quite cool but too expensive for us. Most of us are traditional live broadcast. So it may not be popular soon.

**Comment by keijiro** [comment]
@whitespeed Thanks for the feedback. I thought that NDI is the most affordable format in the next generation IP-based solutions, so I'm a little bit surprised by your response (I mean it's a valuable input). I'll take it into account.

**Comment by Filmengineers** [comment]
Hi @keijiro, is the new version of the desktop video 11 SDK supported?

**Comment by keijiro** [comment]
@Filmengineers Currently I'm not working on this project, so there is no update for the new SDK.
