### ISSUE TITLE
Not Really an Issue

### ISSUE THREAD

**Issue by iiidefektiii** [keijiro/Klinker#3]
I have AVPro Decklink but they do not use DirectShow and connect directly to the hardware capture card. How does your's work? Just curious if it is connecting the same way or if you were able to use DirectShow similar to USB webcams.

**Comment by keijiro** [comment]
Klinker uses DeckLink SDK without DirectShow.

**Comment by keijiro** [comment]
I'm closing the issue. Please feel free to reopen for further questions.
