### ISSUE TITLE
External and Internal Keying

### ISSUE THREAD

**Issue by iurisouz4** [keijiro/Klinker#4]
Can we use external or internal keying in output?
Awesome implementation, i'm using for receive video but struggling to send with key.

Thanks!

**Comment by keijiro** [comment]
First of all, this is just an experimental implementation. Although I know there are some issues with sending/receiving, I have no time for fixing them.

Regarding keying, there is no plan for supporting it. I think you can use 2 SDI outs to use external keying (one for color, and another for alpha).

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
