### ISSUE TITLE
Receive sound from SDK

### ISSUE THREAD

**Issue by JorgeVelez** [keijiro/Klinker#6]
Hi Keijiro,

I see Receiver.h gets **IDeckLinkAudioInputPacket* audioPacket** when the video frame arrives. Have you tried getting the audio stream from the SDK?

The microphone driver seems desynced sometimes.

**Comment by keijiro** [comment]
I've never tried to receive audio packet.

I realized that DeckLink is not enough for my requirements, so I haven't touched it for years.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
