### ISSUE TITLE
Open VPN connection error

### ISSUE THREAD

**Issue by natasha8899** [keijiro/Klinker#7]
The following github forum is explanatory and convincing. I have following queries in this trail that I have setup my router to create a OpenVPN connection and I have installed the OpenVPN app on my Samsung Android phone. Uptil this it worked out fine.
Now I just want to view my cameras using the iVMS-4500 app on my phone, while I'm on the OpenVPN connection. But I don't know anything about what information I have to enter into the app.I have thought that I can choose between HiDDNS - IP/Domain - IP Server, but I think I have to use IP/Domain.
But,when I selecting the  IP/Domain, I entered the IP of my camera (10.0.0.100) in the adresse field, and the portnumber in the port field, and then username and password. But it does not work.And secondly,I am unable to setup VPN server In my Arlo pro 2.Suggest us what to do regarding these [arlo app for pc](https://routerexperts.net/arlo-app-for-pc/) ?for the permanent solution.

**Comment by keijiro** [comment]
I'm pretty sure that you posted in a wrong page. This page is the issue tracker of the Klinker project (Blackmagic Deck Link plugin).

**Comment by keijiro** [comment]
I'm closing this issue now as the question is irrelevant to the project. Please feel free to reopen it if it's actually related to Klinker.
